stages:
  - setup
  - release

variables:
  CI: 'true'

default:
  interruptible: true
  image: node:20.13-slim
  before_script:
    - apt-get update && apt-get install -y git
    - npm install -g nx
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL#https?}/packages/npm/:_authToken=${GITLAB_TOKEN}" >> .npmrc

cache:
  paths:
    - node_modules/

setup:
  stage: setup
  script:
    - npm install
    - npx nx report
  only:
    - tags

release:
  stage: release
  needs:
    - setup
  script:
    - npx nx release publish
  only:
    - tags
